<?php
// use php to show this message to users less than 2 days old
?>
<div class="container">
	<div class="row">
		<div class="col-12 col-12 text-center">
			<div class="alert alert-info alert-dismissable" role="alert">
			  <p>You're most welcome to New cashpoint, we are a social revenue platform.</p>
			  <p>We generate revenue via Ads you interact with, which will be shown to you as soon as our due process is complete.</p>
			  <p>You might have questions about the workings of the site.</p>
			  <p>Rest assured, we are working full time to fully implement a forum, and all required features for you, you can start earning cashpoints now.</p>
			  <p>Post publishing, Comments and reply display, Forum interaction among others will be made available shortly.</p>
			  <p>I removed the countdown to let you navigate the site, however we will be fully be operational by the end of the month as planned.</p>
			  <p>we are hosting our giveaway and urge you to share the links to everyone that wishes to earn for free, slots are limited.</p>
			  <p>we are hosting our giveaway and urge you to share the links to everyone that wish to earn for free, slots are limited.</p>
			  <p>Finally, follow us across all social media to share our content, you earn even more doing so.</p>
			</div>
		</div>
	</div>
</div>